### ISSUE TITLE
Possible bug in Beta Release 

### ISSUE THREAD

**Issue by wanderleihuttel** [jobisoft/TbSync#223]
I'm running the latests Beta version of TbSync 1.0.29 and the latest Beta version of Provider CalDAV e CardDAV 0.10.41.
And I noticed that the contacts are not been synchronized to the cloud.

I'm using a  Zimbra account. If I downgrade to the versions are available in the Thunderbird store the contacts are synchronized fine!

When I make some local modifications, it doesn't appear in the TbSync that were made local modifications.

**Comment by jobisoft** [comment]
Can I have a screenshot of the TbSync manager window of that accoun after you made changes to its contacts?

**Comment by wanderleihuttel** [comment]
Hello @jobisoft ! Yes.
In fact is showing that has local modifications, but even I clicking in the button much times the contacts are not synchronized.

![zimbra](https://user-images.githubusercontent.com/16232272/51671550-527ade80-1fb0-11e9-88d8-e4186e08821d.png)

**Comment by jobisoft** [comment]
You mean, after you click on sync, TbSync is back to "green" and Reports everything has been synced, but it does not actually changes on the Server?

**Comment by wanderleihuttel** [comment]
Yes. That's it!

**Comment by jobisoft** [comment]
I could reproduce that, a patch to fix this is being tested. 

Other Question: 
1. Is your zimbra Server recent/latest version? 
2. Can I have a test account?
3. Can we test sharing stuff and see how TbSync handles that?

**Comment by wanderleihuttel** [comment]
Hello @jobisoft! 
1) The Zimbra Version is "Zimbra 8.7.0_GA_1659 (build 20160628202701)"
2) I'm migrating our emails accounts and I'm using a lab account for testing right now. But I can send you the credentials to test in your email. After I migrate I can send you a definitive account for tests.
3) Yes

**Comment by jobisoft** [comment]
So, new beta is out. Please 
 - disable your account in TbSync
 - update AddOns
 - re-enable
 - try again to make local changes
 - does it work?


If you have credentials so we could test sharing stuff, just send them via email (ist on my main GitHub page)

**Comment by jobisoft** [comment]
Sharing still does not work :-( I filed a bug against zimbra a few months ago, but they have not fixed it yet.
https://bugzilla.zimbra.com/show_bug.cgi?id=109033

**Comment by jobisoft** [comment]
TbSync has no way of detecting shared resources on zimbra, if that bug is not fixed. Are you / your employee a main subscription user, so you have a more powerful voice to get this fixed?

**Comment by wanderleihuttel** [comment]
We are using the previous version of Zimbra, not 8.7.11 but 8.7.0.
But why in the older version works fine and in the Beta no?

I will update and test again.

**Comment by jobisoft** [comment]
I changed a core funtion in the beta to cope with Mailing lists and the new function failed if the cards UID had special chars, which I did not take care of. It is fixed now.

**Comment by jobisoft** [comment]
I do not know if I confused you. The sharing stuff test I did is complety unrelated to the issue you reported. The issue you reported is fixed in the latest beta of TbSync. You do not have to upgrade your Zimbra Server!

**Comment by wanderleihuttel** [comment]
About the issue I've related, I've tested it and is ok.
I guess the shared stuff you are talking is shared contacts and calendars.
How I'm still migrating our environment I'm still not using.
