### ISSUE TITLE
Poor performance - 4mn+ to load one CalDAV calendar with ~4000 items in Thunderbird 68.1.1

### ISSUE THREAD

**Issue by richardleger** [jobisoft/TbSync#305]
## Your environment

TbSync version: 2.4
Thunderbird version: 68.1.1 (32-bit)
Windows: 10 Pro 64bits
Conn Type: Standard ADSL

## Expected behavior
Loading a ~4000items calendar via HTTP takes max 2s... I would expect similar performance when loading calendar in TB via TbSync+DavProvider...

## Actual behavior
Current performance results:
~4m38s|176 Requests - 16.68MB Transferred - Finish: 4mn49s|
Numerous gaps appears between network requests as seen in task manager on Windows 10 wifi performance...

## Steps to reproduce
Updated from TB 68.1 to TB 68.1.1
Run clean new profile (created recently in 68.1), no email account, select All Events in unifinder, no unifinder column selected (default), added TbSync add-on, configured my Caldav account via TbSync... select one calendar with ~4000items, press Synchronise use stop watch to measure loading of items...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I am not responsible for CalDAV sync, Lightning is. I am just setting them up for you. You can remove TbSync and your calendars will still sync.

I am however responsible for contact sync. If you see performance issues there, please try out beta, before creating a new issue.

http://tbsync.jobisoft.de

Thanks.

**Comment by richardleger** [comment]
Those are the gaps between network requests I am talking about...

![image](https://user-images.githubusercontent.com/6603379/65804927-934c7800-e17b-11e9-9d59-927d8dfa5dfd.png)

![image](https://user-images.githubusercontent.com/6603379/65804946-ad865600-e17b-11e9-8f0b-3b980b16b2f6.png)

**Comment by jobisoft** [comment]
Please uninstall TbSync.

**Comment by richardleger** [comment]
So the Provider for CalDAV/CardDAV you use within TbSync is simply "pure" Lightning?

**Comment by jobisoft** [comment]
CalDAV sync is done by Lightning, as I saw no point in implementing that again. 

I am doing resource discovery and account management for CalDAV/CardDAV and CardDAV sync.

**Comment by richardleger** [comment]
That make sense, thanks for confirming. For some reason, I had understood that Provider for CalDAV & CardDAV of TbSync was a different one than Lightning (which I thought was used just for displaying). 

As I have already registered a bug about Lightning performance issues already here https://bugzilla.mozilla.org/show_bug.cgi?id=1572823 I will follow up there then... 

Thanks for your prompt responses.

**Comment by jobisoft** [comment]
Do you see the same issue with (my) CardDAV sync? In TbSync stable I use the same network stack as Lightning, in TbSync beta I use my own one, as Lightning currently cannot use cookies.

**Comment by richardleger** [comment]
FYI, with pure Lightning (without TBSync) setup in a separate profile, the calendar load in 3mn05s but the minute overhead compared with TbSync result above, could be due to the fact that TBSync first check for list of available folders first when you start to synchronise, before synchronising the calendar... which may explain the 1mn difference between the two test environments with the same calendar... still 1mn seems quite long... :-)
With Lightning only, I see about 49 network requests... there were 176 networks request with TbSync+Dav... you may want to allow end-users to synchronise a specific resource without having to check again for all folder list or syncing all resources (at least those for which selection status has not changed)...to reduce network request and allow increased speed... just a thought...

**Comment by richardleger** [comment]
With TBSync+Dav, if I disable TbSync add-on, make sure offline support/reminder are disabled in both cases... if I disable calendar and re-enable it, it would re-sync entirely and I do see the same issue... you are probably right it may likely be in Lightning...  though from the moment calendar is loading, with pure Lightning I see less gaps between network requests in first 20-30 seconds period but after that graph appear more or less the same in Task Manager > Performance > Wifi... I hope I make sense...

**Comment by jobisoft** [comment]
Can you re-verify that for me? If you hit any of the lightning sync buttons (or lightning is doing auto sync upon changes) TbSync is not involved. 

![image](https://user-images.githubusercontent.com/5830621/65812209-31fcc700-e1c4-11e9-8a68-1cad183c9261.png)


Only if you hit the sync button in Tbsync manager, TbSync is looking up the folder list and inits a lightning sync for each calendar resource.

So is there a difference in performance, hitting one of the lightning sync buttons, whether TbSync is enabled or not?

**Comment by jobisoft** [comment]
Also, in the latest beta of TbSync I have reduced the number of network calls, by not doing a full roundtrip anymore, but start from the last known principal. Could you try that as well? 

Thanks for investigating!

**Comment by richardleger** [comment]
> Can you re-verify that for me? If you hit any of the lightning sync buttons (or lightning is doing auto sync upon changes) TbSync is not involved.
> Only if you hit the sync button in Tbsync manager, TbSync is looking up the folder list and inits a lightning sync for each calendar resource. 
> So is there a difference in performance, hitting one of the lightning sync buttons, whether TbSync is enabled or not?

When...

- TBSync Enable - Click Lightning Synchronise button
![image](https://user-images.githubusercontent.com/6603379/65829948-b9b90300-e2a2-11e9-873c-99085d2e7565.png)

- TBSync Enable - Right click Calendar > Synchronise Calendards
![image](https://user-images.githubusercontent.com/6603379/65829968-f684fa00-e2a2-11e9-81dc-48d42c4ec3ca.png)

So it does not look like TBSync is involved as only one network request is sent...

At this stage though the calendar has already been loaded automatically upon startup of TB (e.g locally cached) so pressing the Synchronize button would only look for changes... while my previous test was about loading the initial ~4000 items... which happens every time TB startup if the my Calendar is enabled...

Looking at network traffic when TB startup, I seems to notice that it may be involving TBSync for a first folder list lookup (as per the graph "shape") prior loading the calendar... but I cannot check in TB Network requests as at this stage the DevTools is not up and running yet... I only start it manually via CTRL+SHIFT+I before my testings... which I cannot do upon TB startup... at least I don't know how...

Hope that answer your question...

**Comment by richardleger** [comment]
> Also, in the latest beta of TbSync I have reduced the number of network calls, by not doing a full roundtrip anymore, but start from the last known principal. Could you try that as well?

With TbSync Beta (2.4.11, DAV 1.3.19) the folder list lookup (only) when pressing Synchronise Now button in TbSync UI takes about 14 seconds:
![image](https://user-images.githubusercontent.com/6603379/65830778-84b0ae80-e2aa-11e9-9889-c63d94b840a9.png)
80 network requests seems a lot... just for folder list lookup :-)
(for comparison, with just Lightning, no TbSync involved, the calendar sync only use about 46 requests)

FYI, in my case, I have multiple resources (calendar/addressbook) I can access in my account, from other users that may have shared theirs with me or from shared areas...

Now if I tick my calendar in TbSync UI and press Synchronise Now button, it takes about 4mn16sec to load the entire calendar... this timing include the 14s folder list lookup that is re-triggered by TbSync + Lightning processing (4mn16sec - 14s = 4mn2sec):
![image](https://user-images.githubusercontent.com/6603379/65830949-fe956780-e2ab-11e9-883e-c955a15ff0b9.png)
172 request also seems a lot here...
(for comparison, with TbSync involved,  if I remove the 80 requests used for folder lookup as detected above, it remains 92 network requests just for calendar sync which seems twice as much as pure Lightning option comparatively...)

As reported here (https://bugzilla.mozilla.org/show_bug.cgi?id=1572823#c3) there seems to be some progress with Lightning performance coming up in 70.x branch (~1mn to load the same calendar and more progress to be expected later on)... but still 14sec for TbSync folder list lookup seems long from a computer speed point of view and that is just for one account setup :-) 

Hope that answer your question and may help improve performance somehow...

**Comment by richardleger** [comment]
For the record and comparison for you to see the difference, here is test result with pure Lightning solution (no TbSync installed or involved at all), same version of TB, same calendar, same testing environment:
![image](https://user-images.githubusercontent.com/6603379/65831229-318d2a80-e2af-11e9-967a-405abde4eabe.png)

**Comment by jobisoft** [comment]
This is getting difficult to follow :-) 

Resource discovery does involve a couple of requests, as I have to check multiple principals for ACL information, group information and so on. You can enable debug logging (under Help in the TbSync manager) and you can see what requests TbSync is doing.

The pure time needed for folderlist lookup can be measured by hitting "Sync now" in the manager, with no calender/resource enabled. That is 14s in your case?

Do I understand you correct, that you say with TbSync being enabled, calendar sync is taking twice as long?

**Comment by jobisoft** [comment]
I released a new beta with two extra options for you to test with:

```
extensions.dav4tbsync.debugCreateCalendarsAsEnabled
extensions.dav4tbsync.debugRequestLightningSyncOnSync
```

Both default to `true` , which reflects the current behavior. By setting both two false, TbSync will not do any action on the calendar. It will create them disabled, so you have to enable them to initiate the sync and pressing the sync button in the TbSync Manager will not cause a sync of the calendar resources. Only lightnings own buttons will cause a sync.

It would be intereting to know, what timing you get now.

One question: TbSync is not doing anything on its own. Only if a periodic sync has been enabled or its sync button is pressed. Do you have periodic sync enabled? If not, I do not see, how TbSync could do any network requests during Thunderbird start.

Thanks for your time!

**Comment by richardleger** [comment]
> Resource discovery does involve a couple of requests, as I have to check multiple principals for ACL information, group information and so on. You can enable debug logging (under Help in the TbSync manager) and you can see what requests TbSync is doing.

For my measures above I used my stopwatch and TB > DevTools > Networking
I have ticked option to create debug report in TbSync > Help but where are the debug log files generated? I can't seem to find how to get to them...

> The pure time needed for folderlist lookup can be measured by hitting "Sync now" in the manager, 
>with no calender/resource enabled. That is 14s in your case?

Yes, that is what I did. 
Yes, in my case 14s correspond to the folder list lookup via 80 network requests (according to TB > DevTools > Networking which is where I took print screens from)

> Do I understand you correct, that you say with TbSync being enabled, calendar sync is taking twice as long?

Would this table make more sense to understand and compare?

|#|TB Version| Add-ons|LoadingTime| DevTools > Networking|
|---|---|---|---|---|
|01 | 68.1.1 (32-bit) | Lightning | ~3m05s | 48 Requests - 8.24MB Transferred - Finish: 2mn80s
|02 | 68.1.1 (32-bit) | TbSync+DavProvider | ~4m16s | 172 Requests - 16.68MB Transferred - Finish: 4mn17s

This table means that to load one calendar of ~4000 items it takes:
- 3 minutes 5 seconds via 48 network requests with pure Lightning
- 4 minutes 16 seconds via 172 network requests ( = 80 network requests for folder list lookup + 48 network requests for Lightning supposedly + 44 network request for others???) with TbSync+Dav (stable version)

Note: 
- The 4mn16s includes the 14s corresponding to the folder list lookup done by TbSync...

**Comment by richardleger** [comment]
> * with TbSync+Dav (stable version)

Correction: "with TbSync (beta version 2.4.11) +Dav (beta version 1.3.19)"

**Comment by richardleger** [comment]
I recreated new profile and re-downloaded TbSync and other beta xpi from https://tbsync.jobisoft.de/beta/TB68/

Set the following:
extensions.dav4tbsync.debugCreateCalendarsAsEnabled = false
extensions.dav4tbsync.debugRequestLightningSyncOnSync = false
Help > Debug = disabled (unticked)

> It would be intereting to know, what timing you get now.

As measure in DevTools > Networking...

After press on TbSync > Synchronise Now (with no resource selected) - **9.89s**:
![image](https://user-images.githubusercontent.com/6603379/65835045-89d92200-e2d9-11e9-8ef6-1e0439f64e9a.png)

I clear DevTools > Networking results...

After press on TbSync > Synchronise Now (with only my calendar selected) - **12.54s**:
![image](https://user-images.githubusercontent.com/6603379/65835082-f9e7a800-e2d9-11e9-8b67-f062c6ba0b8d.png)
==> After the folder list lookup completes, my calendar appears in view, just stay turned off and disabled as you expected...

I clear DevTools > Networking results...

After I close TbSync, select my calendar, Right Click > Properties > Tick "Switch this calendar on" > OK - **3.92mn**:
![image](https://user-images.githubusercontent.com/6603379/65835186-3d8ee180-e2db-11e9-98e5-ba74c42a0eb4.png)

> One question: TbSync is not doing anything on its own. Only if a periodic sync has been enabled or its sync button is pressed. Do you have periodic sync enabled? If not, I do not see, how TbSync could do any network requests during Thunderbird start.

I use only default settings here. I don't set any periodic sync or else, just use TB default... so what ever they are... also current performance is as of immediately after setting up the account and syncing calendar first time... so no periodic sync involved I believe... just performance measurement to load one ~4000items network calendar (CalDAV).

All I do is to create a new profile (without email account), add my CA certificate, set Find Events view (unifinder) to All Events, installed TbSync add-ons, add my CalDav account, sync one of my calendar...

Let's forget about the startup issue for now as it is in any case linked to delays observed and measure above (which are more of concern) while TB is already up and running...

**Comment by jobisoft** [comment]
Nice, so the options work as intended.

I guess you can (roughly) reproduce the 3.92 min loading time of you calendar by disabling and re-enabling you calendar. The downloaded data remains 8.25 MB and the time needed to download the calendar is always 4min?

I assume (keeping both extra options at false) that loading time does not change wether TbSync itself is enabled or disabled?

**Comment by jobisoft** [comment]
The debug report is in your profile folder in the TbSync folder. I will add "view report" button to the UI soon.

**Comment by jobisoft** [comment]
Correction to my last-to-last comment:

...  by disabling and re-enabling you calendar _in Lightning_ ... 

Just to be clear.

**Comment by richardleger** [comment]
> Nice, so the options work as intended.

Yes.

> I guess you can (roughly) reproduce the 3.92 min loading time of you calendar by disabling and re-enabling you calendar. The downloaded data remains 8.25 MB and the time needed to download the calendar is always 4min?

Yes, the issue is consistent and I can reproduce it if I disable Offline Support... so it would reload the entire calendar...
![image](https://user-images.githubusercontent.com/6603379/65853704-4a025100-e352-11e9-97fb-4ec1256d6ffa.png)
![image](https://user-images.githubusercontent.com/6603379/65854065-694dae00-e353-11e9-9641-09bbd19b09dc.png)

In this case it is no longer 4mn, it reduce to about 3mn because at this stage it only involves Lightning... no more TbSync... which is what you expected...

The 4mn is only when I press the Synchronise Now from TbSync when it does the 14s folder list lookup + calendar sync the rest of the time...

> I assume (keeping both extra options at false) that loading time does not change wether TbSync itself is enabled or disabled?

TbSync ON/OFF does not make any difference... with regards to Lightning sync speed...
![image](https://user-images.githubusercontent.com/6603379/65854420-7c14b280-e354-11e9-8b47-89609f2b5705.png)

As indicated previously the delay from Lightning is already being worked on here https://bugzilla.mozilla.org/show_bug.cgi?id=1572823.

In this GitHub bug here, I am more concern about the 1mn overhead (including 14s folder list lookup) that TbSync adds on the top of Lightning... I wish it could be reduced somehow :-)

For info, loading my entire calendar as .ics file via http takes no more that 2 seconds max... so having to wait 4mn for TB to load it, is way too much for anyone taste... that is why I am tracking what is going on and report performance issues measured, so it can be fixed via reproducible tests and analyses... for the sake of all users out there :-)

Hope that make sense...

Thanks for your help.

**Comment by jobisoft** [comment]
Now we are getting to the part which I do not understand. And which is the core of this issue:

> In this case it is no longer 4mn, it reduce to about 3mn because at this stage it only involves Lightning... no more TbSync... which is what you expected...
>
> The 4mn is only when I press the Synchronise Now from TbSync when it does the 14s folder list lookup + calendar sync the rest of the time...

With both debug options set to false, TbSync is not doing anything except the folder list lookup (14s) when you click on the TbSync sync button. After those 14s (or something), TbSync switches back to idle and there should be no more network traffic at all. It is not initiating a lightning sync so there cannot be any overhead produced by TbSync.

Where is than 1min coming from? What is he doing in that 1min? I am really puzzled....

**Comment by jobisoft** [comment]
A general info: fetching an ics file (pure data) and parsing it to load it into a UI are two different things. You will always take longer to "load" a calender in terms of reading its content and adding the events to the calendar. Also, you usually do not download all events at once, but go in chunks, so the task can be distributed and the UI does not freeze (TB is not multi threading). 

But 4min is a lot, that is true, but we will never be as fast as 2 sec :-)

**Comment by richardleger** [comment]
> A general info: fetching an ics file (pure data) and parsing it to load it into a UI are two different things. You will always take longer to "load" a calender in terms of reading its content and adding the events to the calendar. Also, you usually do not download all events at once, but go in chunks, so the task can be distributed and the UI does not freeze (TB is not multi threading).
> 
> But 4min is a lot, that is true, but we will never be as fast as 2 sec :-)

I understand and I agree... 

My point was just to show the current HUGE gap... 3-4mn in computer time is a lot of time... even 2 seconds :-)

I am sure there must be way for TB, Lightning and TbSync teams, to find ways to improve current on going performance issues at every level... to make sync, parsing and display of calendar items much much much faster than currently... at least I am hopping so... 

After email, calendaring is the most used feature in TB so it needs more care and attention in term of performance... I am trying to raise awareness about this as much as I can so developers can integrate it in their dev process and testing...

Again 1mn overhead caused by TbSync shall be considered as an issue that needs to be fixed... because if you have more than one calendar (which is the case for most workers) then you end up multiplying delay as much calendar you have... 12mn for x3 calendars?

At the moment responsiveness of TB remain slow during calendar loading which does not help either... but it is improving over time...

**Comment by jobisoft** [comment]
Can you investigate that 1min overhead and be more specific, when it occurs and what he is doing in that 1min?

I cannot do anything about that without more details.

For me it is unexplainable where that is coming from, as the two debug options have instructed TbSync to not touch your calendar. This is the what I do not understand:

> With both debug options set to false, TbSync is not doing anything except the folder list lookup (14s) when you click on the TbSync sync button. After those 14s (or something), TbSync switches back to idle and there should be no more network traffic at all. It is not initiating a lightning sync so there cannot be any overhead produced by TbSync.

> Where is than 1min coming from? What is he doing in that 1min? I am really puzzled....

**Comment by richardleger** [comment]
> Can you investigate that 1min overhead and be more specific, when it occurs and what he is doing in that 1min?

The 1mn overhead only appears if TbSync enabled, the two debug options are not specifically set to false (just use default value as per default install), my calendar is selected in my TbSync account, press the TbSync > Synchronise Now button to trigger first sync of the calendar (so the entire calendar is loaded).

> I cannot do anything about that without more details.

I understand and I will send you TbSync debug file shortly... though having the UI button to access them easily would help (don't worry for now I'll get the file manually) :-)

> For me it is unexplainable where that is coming from, as the two debug options have instructed TbSync to not touch your calendar. This is the what I do not understand

The 1mn overhead does NOT appear if the two options you mentioned are set to false.

As per test done previously, it looks like the overhead is due to 44 extra network requests... could it be that Lightning network requests are triggered twice somehow in that case instead of just once perhaps? 

Looking at the TbSync debug log and the TB > Tools > DevTools > Network requests may give insight perhaps... I am not sure how best to send you the later in a file... I can't seems to have a way to save network requests I see in a file...

**Comment by jobisoft** [comment]
The view debug log button is in the latest beta (just released).

Your last comment put me back on track. Can you identify, which option is causing the overhead?

CreateCalendarsAsEnabled : true
RequestLightningSyncOnSync : true
-> overhead

CreateCalendarsAsEnabled : false
RequestLightningSyncOnSync : false
-> no overhead

CreateCalendarsAsEnabled : false
RequestLightningSyncOnSync : true
-> ??

CreateCalendarsAsEnabled : true
RequestLightningSyncOnSync : false
-> ??

**Comment by richardleger** [comment]
> As per test done previously, it looks like the overhead is due to 44 extra network requests... could it be that Lightning network requests are triggered twice somehow in that case instead of just once perhaps?

FYI, just to confirm my suspicion, when overhead is observed, each REPORT query seems to be send twice on the network, see in print screen below... notice the same size appearing twice in two successive network requests...

![image](https://user-images.githubusercontent.com/6603379/66050695-95208d80-e525-11e9-9751-d71871395fa1.png)

**Comment by richardleger** [comment]
> Can you identify, which option is causing the overhead?

Done, see below...

> CreateCalendarsAsEnabled : true
> RequestLightningSyncOnSync : true
 
**-> overhead**
**~1mn**/176 network requests **=** **14s**/80 requests for folder list lookup + **~46s**/96 requests (instead of just 46 requests via pure Lightning option - about twice as less)

> CreateCalendarsAsEnabled : false
> RequestLightningSyncOnSync : false

**-> no overhead**

> CreateCalendarsAsEnabled : false
> RequestLightningSyncOnSync : true

-> **no overhead**

> CreateCalendarsAsEnabled : true
> RequestLightningSyncOnSync : false

-> **no overhead**

Please note again that by pressing the Synchronise Now button in TbSync the folder list lookup is always triggered (14s/80 requests overhead) in all cases...

**Comment by jobisoft** [comment]
I have the same suspicion, and I expected the result of your tests. I will try to fix this and release a new beta soon. I will report back.

**Comment by jobisoft** [comment]
I just released a new beta. Simply click on the gear menu -> Update addons to get the new version.

Changed behaviour of the TbSync "Sync now" button:

This beta is not sending a "sync" command to lightning, if the calendar has just been created and thus the sync command has already been send as part of the "create" command.

This is the only place I could think of, where the double sync could happen. So I hope the 1min overhead is gone now. 

I still do folder lookup each time you hit the TbSync Sync button, as this is what that button is doing: Updating the folderlist and then syncing each resource found. If you just want to sync an existing calendar, use the lightning sync buttons.

The two debug options have been removed and are ignored by this beta, id they are (still) set.

What is the overhead status?

**Comment by richardleger** [comment]
> What is the overhead status?

**The good news:** The dual request issue seen before has now disappeared
**The bad news:** It has **NOT fixed** the overhead... which now again happens every time... something else must be going on... One thing I noticed is that when synchronizing via TbSync the Reminders window appears multiple times while it does not seem to happen with pure Ligthning (no TbSync installed or involved). Something else must be different somehow... I will keep looking...

See re-test result below...

- 68.1.1 (32-bit) fresh profile re-created for both TbSync tests and pure CalDav tests
- Fresh re-install of TbSync Beta 2.4.18 installed
TbSync default observed:
-- debug disabled in Help
-- NOT exist extensions.dav4tbsync.debugCreateCalendarsAsEnabled 
-- NOT exist extensions.dav4tbsync.debugRequestLightningSyncOnSync 
- set All Events in unifinder view 

With TbSync Sync Now and debug options...

missing, missing = overhead (~**1mn42**+)
**4mn40s** total = 14s folder list lookup + 4mn26s sync

true, true = overhead
not measured

false, false = overhead (~**2mn02**+)
**5mn**/154 requests
![image](https://user-images.githubusercontent.com/6603379/66253530-afdf4600-e761-11e9-9eb3-c5294c6047b6.png)

Pure Lightning/CalDav (no TbSync installed or involved) = **no overhead :-)**
**2mn58**/49 requests
![image](https://user-images.githubusercontent.com/6603379/66253462-925dac80-e760-11e9-94e3-2d9123716d63.png)

**Comment by jobisoft** [comment]
What timezone are you in? Would you say yes to a teamviewer session so I can have a look?

I am not able to understand your findings, as the presence of the debug options is ignored: they do not do anything, and they should not make it worse...

*puzzled*

**Comment by richardleger** [comment]
I think I got it... silly me!!! It is the Offline Support mode of Lightning that make it worth (create most of the overhead) TbSync have it set Enabled by default in a separate Options tab I had not noticed till now! 

Indeed when I do my test via CalDAV this option is Disabled (I do it manually every time I setup network CalDAV calendar) simply because at the moment I am more interesting at improvement in online synchronization/loading... Offline Support will be another matter later... it might be fixed by then :-) Sorry was my mistake... at least we fixed the dual network request issue :-)

As the Offline Support option can be set per each calendar, I would suggest to move it from Options tab to Synchronization Status tab and make it available to tick/untick for each calendar, etc... because end-users (like me) may want to use Offline Support for some calendar but not necessarily all of them :-) that goes for other resources as well...

Is the current beta version of TbSync usable in any upper version of TB including those on beta and daily channels? I would like to run more tests on those as well... but with regards to this bug we can consider it closed!

By the way thanks for your help and for the UI button to access logs, very handy :-)

**Comment by jobisoft** [comment]
Ah, what a relief :-)

TbSync is currently not compatible with Beta or Daily. After the announced end of legacy support after TB72, I need to evaluate my next steps, as I have to learn WebExt from scratch. Spending time on my current legacy AddOn for TB70 and TB71 sounds like a waste of time.

**Comment by richardleger** [comment]
No worry, I understand that is why I was asking :-)

Here may be good resources to get started at converting legacy add-on to mailExtension (aka WebExtension for Thunderbird) which would be compatible from 68.x branch onward:
https://developer.thunderbird.net/add-ons/updates
https://developer.thunderbird.net/add-ons/updates/overlays
https://thunderbird-webextensions.readthedocs.io/en/68/

You shall also be able to publish both legacy and mailextention on the ATN but you would certainly better know than me :-)

There is also a big revamp of Thunderbird interface/theme planned for 76 version... so you know...

In any case you may be able to get advise from dev team, I recall someone saying on tb-planning mailing list that has converted multiple legacy add-on but I don't recall exactly who... you would need to check on recent archives of the mailing list (within the past two months)....

If that can be of any help...

**Comment by jobisoft** [comment]
Hehe, I am the author of 
https://developer.thunderbird.net/add-ons/updates

:-) 

(see very bottom of those pages)

The issue is, that we have a "naming" problem now. Technically, all addons had to be converted to WebExtensions for TB68, because they need to have a manifest.json. But we could still use the "old" coding techniques (overlay or bootstrap) as we could enable a legacy mode in manifest.json.

That legacy mode is going away. We now need to convert to real/true WebExtensions. This will cause confusions. When we just say "we need to convert to WebExtensions" some might think, they are fine, which is not true. I will update the guide shortly to point that out.

The needed update for Addons for TB78 ESR (there was a shift in ESR schedule) will be huge. I am actually afraid of what is ahead.
