### ISSUE TITLE
Autodiscover feature has a negative timeout value

### ISSUE THREAD

**Issue by pd5rm** [jobisoft/TbSync#350]
## Your environment

TbSync version: 2.9
ActiveSync Provider: 1.9
Thunderbird version: 68.3.0

## Expected behavior
If the autodiscover feature is used to signup a new account, the trackdown counter goes into negative territory. See screenshot.

## Actual behavior
Stop at 0? And show timeout/error dialog of some sort maybe?

## Steps to reproduce
Use autodiscover feature to create new account, and make show the domain/endpoint is not reachable?

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by pd5rm** [comment]
![negative-timeout](https://user-images.githubusercontent.com/1731288/71045578-46c56880-20ea-11ea-92f9-ca8e378030d0.png)

**Comment by jobisoft** [comment]
Is that reproducable? Anything in the debug log? In the event log?
Does it happen with beta as well?

**Comment by pd5rm** [comment]
Yes, reproducible with stable and beta.

I see a couple on these entries on console:
JavaScript error: chrome://eas4tbsync/content/includes/sync.js, line 57: Error: 

when click on debug.log in ui
JavaScript error: chrome://messenger/content/tabmail.xml, line 793: TypeError: tab is undefined

The dialog gets stuck, and unresponsive to being closed. Need to kill off the TB process.

Can I send the log to private address, since there's lot of HTML content and not easily redactable via find/replace.

**Comment by jobisoft** [comment]
Yes please send the log via the build-in error reporting at „help“ in the TbSync Account Manager.

**Comment by jobisoft** [comment]
I would love to fix this, but I need a debug log.

**Comment by jobisoft** [comment]
I just released a new beta, which may fix our issue. Wanna try?
https://tbsync.jobisoft.de

**Comment by pd5rm** [comment]
Hi there,

I just tried with TbSync 2.10, and still see the countdown go past 0 into negative offsets.

Repro Case:

1. Open TbSync account manager dialog
2. Click account actions
3. Add new account 
4. Select Exchange
5. Enter a valid username, but invalid password (to cause the timeout)
6. Click Autodiscover settings button
7. See the timeout counter go negative.

**Comment by jobisoft** [comment]
Could you email me the username you are using? I cannot repro this with my test accounts. Maybe it is a response from your server, that is causing this. My email is listed on my [main github page](https://github.com/jobisoft).

**Comment by jobisoft** [comment]
@pd5rm : Could you email me the username you are using? I cannot repro this with my test accounts. Maybe it is a response from your server, that is causing this. My email is listed on my main github page. Thanks for your help.

**Comment by pd5rm** [comment]
My username connects to a internal corporate exchange server, so I don't think it would be of much use for testing.

**Comment by jobisoft** [comment]
Ok, can you open the developer console (Tools - Developer Tools - Developer Console) before adding your account and check if any error is showing up there when your issue occurs?

**Comment by pd5rm** [comment]
Hi,

I see the following stacks in developer console:

```
Handler function threw an exception: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsICacheInfoChannel.isRacing]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://devtools/server/actors/network-monitor/network-response-listener.js :: NetworkResponseListener.prototype._getSecurityInfo< :: line 334"  data: no]
Stack: NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/server/actors/network-monitor/network-response-listener.js:334:26
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22
onStartRequest@resource://devtools/server/actors/network-monitor/network-response-listener.js:226:10
Line: 334, column: 0`
```
I see several of the below, with different "guids".
```
XML Parsing Error: syntax error
Location: moz-nullprincipal:{f294188d-21bf-4673-848c-5de3b0aabaf2}
Line Number 1, Column 1:
```

and a bunch of these (I assume this is your code). There's no logging string there, just a line number.
```Error: sync.js:57:17```

I updated to latest betas as of this morning.

**Comment by jobisoft** [comment]
This is going to be difficult. May I ask you again to send me your username via private email? The first query goes to microsoft, not to your on-prem server. I need to see that response.

**Comment by jobisoft** [comment]
I just released a new beta including this fix, but I will also release a new stable within a couple of hours, so you may just wait for the next stable release instead of switching to the beta release channel:
https://tbsync.jobisoft.de

However, I assume this will still not work for you - but now with a proper error message: Your server does not support Exchange ActiveSync.

I will report, when this fix hits the stable release channel.

**Comment by jobisoft** [comment]
Released.
