### ISSUE TITLE
Unable to sync recurring Calendar updates to Google Calendar.

### ISSUE THREAD

**Issue by kianhui86** [jobisoft/TbSync#436]
## Your environment

TbSync version: 2.16
Thunderbird version: 78.2.2

No, I have not installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Actual behavior
When a reminder from a recurring event is triggered in thunderbird, we are unable to dismiss it.

Triggers Error Message: This item has recently been changed on the server. Submitting your changes will overwrite the changes made on the server.

2 buttons available to click: (1) Submit my changes anyway, (2) Discard my changes and reload.

Both options does not work.

## Steps to reproduce
When a reminder from a recurring event is triggered in thunderbird, click on (1) Submit my changes anyway. It will continuously trigger the same message as it continues to fail.

This can also be triggered by editing a recurring event on thunderbird (Recurring event to be created in google calender)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I will forward it once I extract the file. I only just turn debugging on and It seems like after turning it on; Now thunderbird is not showing recurring events anymore. I checked my google calendar the event is still there.

**Comment by Oxalin** [comment]
As a side note to the fact that your recurring events aren't shown anymore : on my side, from time to time, for the recurring event bug that you are experiencing, the events will not show in the reminder window until I restart TB or resync calendars. The bug (unable to dismiss / snooze recurring events) is only hidden by something else that I'm still trying to figure out.

**Comment by kianhui86** [comment]
Noted on the feedback and thank you for looking into this.

**Comment by jobisoft** [comment]
Fixed in latest beta?
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

**Comment by lorenzk1** [comment]
Thunderbird 78.3.3
Newest Beta from Oct 10

Sorry to say: Problem dismissing recurring events still exists. No change in behavior.

**Comment by jobisoft** [comment]
I no longer support google, new accounts can not be created anymore. This is a personal decision.

**Comment by lorenzk1** [comment]
Since two days confirmations of single items of recurring calender events are synced properly.
No idea, why it works now and did not work in the last months. Maybe Google changed something...
Actual Thunderbird 78.5.0 (64-Bit), extensions.dav4tbsync.googlesupport;true
TBSync (not beta...) 2.19 form 11/19
Provider für CalDAV & CardDAV 1.24 from 11/21

Thanks for great extensions, jobisoft!

**Comment by lorenzk1** [comment]
Sorry to say: After a few days the problems are back.
It seems to me, that these issues might have nothing to do with tbsync etc. but with some Google-policies. At least I do not understand, what's going on. The situation reminds me of a problem with gContactSync several years ago after a change in Google-Api, when suddenly all hit rates counted to the developer instead of the costumer...

With "reminders" turned off and after re-sync everything is working fine again.
