### ISSUE TITLE
After restarting TB91, write protection of nextcloud calendar disappears by itself

### ISSUE THREAD

**Issue by gerdlimbeck** [jobisoft/TbSync#531]
## Your environment
Win 10 Pro
TbSync version: 3.0.1
Thunderbird version: 91
## Expected behavior
Write protection should remain after restart 

## Actual behavior
Write protection disappears after restart 

## Steps to reproduce
In addition to Google calendars, I also subscribed to a nextcloud calendar via TbSnyc. This should be write-protected. I selected it in the properties. 
![Schreibgeschützt](https://user-images.githubusercontent.com/58742366/130580198-0a839c3a-4c5a-4b41-ad2b-4a24904eebd9.png)

After restarting TB write protection disappears .
![NichtMehrSchreibgeschützt](https://user-images.githubusercontent.com/58742366/130580196-040e4621-5885-462a-bb21-61264d54f9e8.png)
Occurs for me only with the Nextcloud calendar, not with Google calendar.

**Comment by gituser789** [comment]
Found this: https://bugzilla.mozilla.org/show_bug.cgi?id=1729235

**Comment by jobisoft** [comment]
Fixed by that bug?

**Comment by gerdlimbeck** [comment]
I don't know...

It still occurs with
Thunderbird version: 91.2.0
TbSync version: 3.0.1

**Comment by jobisoft** [comment]
Fixed now?

**Comment by gerdlimbeck** [comment]
Yes, fixed!
Thunderbird version: 91.2.1 (64-Bit)
TbSync version: 3.0.1

Thank you!
