### ISSUE TITLE
TbSync is incompatible with the new Thunderbird release 136

### ISSUE THREAD

**Issue by ewolff** [jobisoft/TbSync#744]
Thunderbird 136 has been released and is in fact the default download. Upgrading to this release disables TbSync.
However, you can downgrade:
- Uninstall 136
- Download 128.8 from https://archive.mozilla.org/pub/thunderbird/releases/128.8.0esr/
- Open compatibility.ini in your profile directory ( AppData\Roaming\Thunderbird/Profiles\ in your Windows home directory on Windows)
- Remove the line that start with LastVersion=
Afterwards Thunderbird should work again. I had to restart it once or twice.

**Comment by DV-P-Butzelaar** [comment]
Same here on Arch Linux. Not just **TbSync**, also the **Provider for Exchange ActiveSync**:

![Image](https://github.com/user-attachments/assets/d5fd5c59-e4e5-46f1-849a-4386555febc2)

**Comment by PeterButzelaar** [comment]
Same here on Arch Linux. Not just **TbSync**, but also **Provider for Exchange ActiveSync**:

![Image](https://github.com/user-attachments/assets/adcd304c-6f1e-43d7-a13c-398986575f44)

**Comment by r3dpan** [comment]
Is there an ETA yet when we can expect a new version of the addon compatible to TB 136?

**Comment by jobisoft** [comment]
Did you manually move to the monthly release channel?

**Comment by sleeksorrow** [comment]
Manjaro has moved thunderbird on stable branch to version 136 and has updated automatically for me.
https://manjaristas.org/branch_compare?q=%5Ethunderbird%24

**Comment by r3dpan** [comment]
I did not update from TB 128 to TB 136 yet. TB 136 is now the default version when downloading TB from the official website tho. Mozilla currently also recommends to manually install TB 136 over TB 128 if you don't want to remain in esr channel / want to switch over to the now officially recommended release channel.

**Comment by stephzero1** [comment]
> Manjaro has moved thunderbird on stable branch to version 136 and has updated automatically for me. https://manjaristas.org/branch_compare?q=%5Ethunderbird%24

I confirm that too on Endeavouros.

Any chanche to get all those extension to be ported on 136 soon or @jobisoft do you suggest to downgrade to 128?
Thanks for your work!

**Comment by Anonymo** [comment]
Since Thunderbird has moved past v128, but Betterbird is still on v128, would it be advisable to move to it?

https://aur.archlinux.org/packages/betterbird-bin

> Thanks for the suggestion. However, it is not so easy, at least on Archlinux. Indeed, the `icu` dependency should also be downgraded, but this library is also needed by other software.
> 
> Of course, the main issue for me, it's the fact that my employer force me to use a mail and agenda provider that is not following open standards.
> 
> Edit: Oh, I didn't saw that issue: [#743](https://github.com/jobisoft/TbSync/issues/743)

**Comment by iGormilhit** [comment]
@Anonymo 

> Since Thunderbird has moved past v128, but Betterbird is still on v128, would it be advisable to move to it?
> 
> https://aur.archlinux.org/packages/betterbird-bin
> 
> > Thanks for the suggestion. However, it is not so easy, at least on Archlinux. Indeed, the `icu` dependency should also be downgraded, but this library is also needed by other software.
> > Of course, the main issue for me, it's the fact that my employer force me to use a mail and agenda provider that is not following open standards.
> > Edit: Oh, I didn't saw that issue: [#743](https://github.com/jobisoft/TbSync/issues/743)

I wasn't aware of this project, thanks. Indeed, it's possible to install it (the binary does help). But since my profile has been opened with Thunderbird 131 and then 136, it may be not a good idea to open it with Betterbird 128. At least, it is what a warning popup suggested when I tried.

So, I will have to start with a new profile. I will consider it.

**Comment by IGeraGera** [comment]
> I wasn't aware of this project, thanks. Indeed, it's possible to install it (the binary does help). But since my profile has been opened with Thunderbird 131 and then 136, it may be not a good idea to open it with Betterbird 128. At least, it is what a warning popup suggested when I tried.

Assuming Linux. You can 1) backup you profile 2) downgrade Thunderbird 2) open the profile with 
`thunderbird -profilemanager --allow-downgrade`

**Comment by jobisoft** [comment]
> I wasn't aware of this project, thanks. I

That is not very helpful advice. Thunderbird ESR is still at 128. For whatever reason you got moved to the monthly release channel which is now at 136. This is the same concept Firefox is using.

The developer of BB is banned from Mozilla for various reasons and I do not want to see his project mentioned on these pages.

**Comment by iGormilhit** [comment]
@jobisoft That's another information I wasn't aware of. The fact is, I've never was on Thunderbird ESR. Just on the version of Thunderbird distributed by the Linux distribution I'm used to. I do understand that tbsync is not anymore available for the version of Thunderbird I'm using. I accept that, and I'm grateful for the work that have been done to make tbsync possible.

I'm going to keep the version of Thunderbird that is easily available for me. I repeat that from my point of view, the actual issue is the fact that my employer force me to use a e-mail and calendar service that isn't standard.

**Comment by jobisoft** [comment]
I just updated my other add-on [Quicktext](https://github.com/jobisoft/quicktext/releases/tag/v5.17). I will now try to get TbSync working, but I cannot say how quickly that will go. I *hope* the weekend will be enough time.

**Comment by jobisoft** [comment]
Can you give these a spin?

[TbSync_4_13.zip](https://github.com/user-attachments/files/19263581/TbSync_4_13.zip)
[EAS-4-TbSync_4-13.zip](https://github.com/user-attachments/files/19263582/EAS-4-TbSync_4-13.zip)

**Comment by ngandrass** [comment]
@jobisoft Thanks a LOT for updating the extension ❤ 

Reading calendars and editing events seem to work flawlessly on Thunderbird v136.0 (64-bit)! 🎉

**Comment by r3dpan** [comment]
@jobisoft 
I tried installing both TbSync_4_13 and EAS-4-TbSync_4-13 after upgrading to TB136.
For some reason, TbSync seems not to recognise the EAS provider addon after each restart of TB. Every time i restart TB i now have to manually disable and re-enable the EAS-4-TbSync addon for TbSync to recognise it.

![Image](https://github.com/user-attachments/assets/347b79a8-4958-44e4-a4ce-3a7c3a267ab6)

Even with TbSync recognising the EAS provider addon TbSync  doesn't seem able to synchronise with my O365 account any more. When manually synchronising (or disabling and re-enabling the account) it tries to send device data -> times out -> retries sending device data -> error. Wasn't able to fix that myself yet tho.

![Image](https://github.com/user-attachments/assets/7b287e56-4eaa-4371-b390-9a22da86b2bb)

**Comment by ngandrass** [comment]
I can reproduce the problem @r3dpan described after restarting TB. During my first test I just updated both extensions and did not restart TB.

After a fresh restart of TB, disabling and re-enabling the EAS provider also solves the problem for me until the next restart.

**Comment by jobisoft** [comment]
Fixed?

[EAS-4-TbSync_4_14.zip](https://github.com/user-attachments/files/19265315/EAS-4-TbSync_4_14.zip)

**Comment by ngandrass** [comment]
> Fixed?
> 
> [EAS-4-TbSync_4_14.zip](https://github.com/user-attachments/files/19265315/EAS-4-TbSync_4_14.zip)

Yes! 👍

**Comment by r3dpan** [comment]
The problem with the EAS provider addon not getting recognised by TBSync seems fixed with EAS-4-TbSync_4_14. OAuth 2 looks still broken tho as i'm still unable to sync my O365 account.

**Comment by jobisoft** [comment]
> The problem with the EAS provider addon not getting recognised by TBSync seems fixed with EAS-4-TbSync_4_14. OAuth 2 looks still broken tho as i'm still unable to sync my O365 account.

Try disconnecting and reconnecting your account. I have no other idea as I do not see a code issue. Anything on the error console?

**Comment by jobisoft** [comment]
Wait, do you see this?

![Image](https://github.com/user-attachments/assets/7fc0349e-242b-4542-8b5f-18924c617f07)

**Comment by jobisoft** [comment]
Found a glitch which may prevent future updates do to aggressive caching. 
* Please uninstall the other pre-release versions. 
* Close Thunderbird
* Make sure that no Thunderbird process running
* Start Thunderbird
* Install the following vesions:

[TbSync_4_15.zip](https://github.com/user-attachments/files/19266839/TbSync_4_15.zip)
[EAS-4-TbSync_4_15.zip](https://github.com/user-attachments/files/19266840/EAS-4-TbSync_4_15.zip)

**Comment by r3dpan** [comment]
> > The problem with the EAS provider addon not getting recognised by TBSync seems fixed with EAS-4-TbSync_4_14. OAuth 2 looks still broken tho as i'm still unable to sync my O365 account.
> 
> Try disconnecting and reconnecting your account. I have no other idea as I do not see a code issue. Anything on the error console?

Sorry for the late reply. I took some time to test different things out.
I tried disabling and re-enabling my (private) O365 account a couple of times but this didn't really work at all (syncloop error). Therefore i proceeded to completely remove the account from TbSync and add it again via add account > Exchange ActiveSync > Microsoft Office 365.
I then entered my *@outlook.de mail from my O365 account and the password which then prompts me for MFA authentication. After that i now get a completely different error:

![Image](https://github.com/user-attachments/assets/f5461435-d709-49da-aed5-6c755594d0b0)

To me this looks like that the EAS provider addon doesn't seem to get the expected necessary response from the server that it tries to sync to. 
Looking at the account settings it seems like the addon tries to connect to 'eas.outlook.com'. As i had kinda similar trouble in the past with the addon because of microsoft just changing their url i tried a couple of other urls (for ex. outlook.office365.com) in the settings but none of those seemed to fix the problem.

Eventprotocol:

![Image](https://github.com/user-attachments/assets/55a0266e-07a8-4014-9b1b-671511002748)

Debugprotocol:

```
** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Start (4.13)

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Thunderbird] : 136.0 on WINNT

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <db>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <addressbook>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <lightning>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <eventlog>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <core>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <passwordManager>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <network>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <tools>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <manager>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <providers>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <messenger>] : OK

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <db>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <addressbook>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <lightning>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <eventlog>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <core>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <passwordManager>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <network>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <tools>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <manager>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <providers>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <messenger>

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Done

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : Default timezone has been found.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Ciudad_Juarez> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Antarctica/Troll> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/AST4> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/AST4ADT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/CST6> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/CST6CDT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/EST5> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/EST5EDT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/HST10> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/MST7> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/MST7MDT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/PST8> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/PST8PDT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/YST9> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <SystemV/YST9YDT> cannot be mapped to any Exchange timezone.

** Sat Mar 15 2025 23:25:32 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loaded provider] : eas::Exchange ActiveSync (4.14)

** Sat Mar 15 2025 23:25:39 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: prepare.request.options, Account: Testing

** Sat Mar 15 2025 23:25:39 GMT+0100 (Mitteleuropäische Normalzeit) **
[Sending] : OPTIONS https://eas.outlook.com/Microsoft-Server-ActiveSync

** Sat Mar 15 2025 23:25:40 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: send.request.options, Account: Testing

** Sat Mar 15 2025 23:25:40 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: eval.request.options, Account: Testing

** Sat Mar 15 2025 23:25:40 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : InvalidServerOptions


** Sat Mar 15 2025 23:25:45 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : InvalidServerOptions


** Sat Mar 15 2025 23:25:45 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: accountdone, Account: Testing
```

**Comment by jobisoft** [comment]
Hm, outlook.com also does not work for me. I have seen that error before, the server sends an invalid redirect. I think waiting a few days resolved it.

**Comment by fonic** [comment]
I'm experiencing the same issues. Lots of "Server issued redirect, retry in 5 seconds" and "The server does not provide information about the supported ActiveSync versions".

Thinks worked perfectly fine before upgrading to TB 136. Tried deleting + readding the account, but that doesn't seem to have any effect.

**Comment by fonic** [comment]
I noticed something odd:
When deleting + readding the account, no OAUTH2 takes place, i.e. the account just gets readded after providing the email address with no further questions asked. How does that work? I also deleted the saved password for TBSync, but still, no reauthorization. Might that be a pointer to what is wrong?

**Comment by jobisoft** [comment]
You can clear the cookies (Tools -> Clear History). It will bring up the OAUTH prompt again, but it will still fail.

I tried on TB128 and there it works. I will try to investigate.

**Comment by fonic** [comment]
Too bad. Thank you very much for working on this!

**Comment by DavidBE-UK** [comment]
Ooh. Only just seen this.. Thanks for looking at this again.

I've updated TbSync and EAS4TbSync to 4.15 and am now getting the interface again in TB 136. But after deleting then trying to re-create my outlook.com account, autodiscover fails, and trying manually I just get a 401 could not authenticate. It is, though, possible I'm not specifying the right server. I vaguely remember having trouble finding the right server address to enter into TbSync after a change a few years ago, and I stupidly didn't check and note which server address I had been using before trying deleting and recreating the Outlook.com account when TbSync failed (but still opened the interface) when I updated TB to 135 a few weeks ago. I'll wait, then, until it appears others here have outlook.com addresses working.

**Comment by fonic** [comment]
> But after deleting then trying to re-create my outlook.com account, autodiscover fails, and trying manually I just get a 401 could not authenticate. It is, though, possible I'm not specifying the right server. I vaguely remember having trouble finding the right server address to enter into TbSync after a change a few years ago, and I stupidly didn't check and note which server address I had been using before trying deleting and recreating the Outlook.com account when TbSync failed (but still opened the interface) when I updated TB to 135 a few weeks ago.

The server is _eas.outlook.com_ but it won't really matter until the issues with TB 136 are resolved.

**Comment by jobisoft** [comment]
> Ooh. Only just seen this.. Thanks for looking at this again.
> 
> I've updated TbSync and EAS4TbSync to 4.15 and am now getting the interface again in TB 136. But after deleting then trying to re-create my outlook.com account, autodiscover fails, and trying manually I just get a 401 could not authenticate. It is, though, possible I'm not specifying the right server. I vaguely remember having trouble finding the right server address to enter into TbSync after a change a few years ago, and I stupidly didn't check and note which server address I had been using before trying deleting and recreating the Outlook.com account when TbSync failed (but still opened the interface) when I updated TB to 135 a few weeks ago. I'll wait, then, until it appears others here have outlook.com addresses working.

It looks like you used the first setup option. Outlook definitely needs the 3rd setup option, to trigger OAUTH. However, as @fonic pointed out, something is preventing that to work in 136.

**Comment by jobisoft** [comment]
I just checked Thunderbird 128 again and there Outlook works.

Those of you who know a bit more about network traffic, cookies, headers and payload data and are able to tap into the connections from Thunderbird to eas.outlook.com: It would really help me to know the difference in the communication of TB128 and TB136.

Thanks for your help!

**Comment by r3dpan** [comment]
@jobisoft 
I have taken a look at the network traffic of TbSync and EAS4TbSync in TB 128 and TB 136. Especially at the point of what happens if you manually trigger the sync of an already configured O365 account.

When looking at the different packages sent out from TB 128 after clicking the sync button inside TbSync there always seem to be 3 packets that get sent before the actual data sync happens.

1. A tunnel is created to eas.outlook.com (Port 443) -> Response 200
2. A OPTIONS request is sent to eas.outlook.com/Microsoft-Server-ActiveSync -> Response 451 including a 'DefaultAnchorMailbox'-Cookie
3. A OPTIONS request is sent to eas.outlook.com/Microsoft-Server-ActiveSync including the set 'DefaultAnchorMailbox'-Cookie -> Response 200
4. ----- actual data gets transmitted ----

I now reproduced the same behaviour on TB 136 and compared the observed packets:

1. A tunnel is created to eas.outlook.com (Port 443) -> Response 200
2. A OPTIONS request is sent to eas.outlook.com/Microsoft-Server-ActiveSync -> Response 451 including a 'DefaultAnchorMailbox'-Cookie
3. ----- nothing happens / TbSync-Error ----

Therefore, i think TbSync_4_15 and/or EAS-4-TbSync_4_15 fails to send the second OPTIONS request with the neccessary 'DefaultAnchorMailbox'-Cookie set during the EAS communication to receive any more data.
To further validate this, i repeated the steps above in TB 136 and intercepted a OPTIONS request before it actually got sent to the server. I then edited the request and inserted the necessary cookie -> I receive actual data for syncing.


Request headers without cookie:
![Image](https://github.com/user-attachments/assets/d594a5aa-ed56-48f6-9fb3-1ac535f2de39)

Request headers with cookie:
![Image](https://github.com/user-attachments/assets/27a41829-1e50-4c6e-919b-acba76619cbb)


I hope this information helps you to further analyse the problem 😊.

**Comment by jobisoft** [comment]
@r3dpan Thanks for your analysis, that helped to understand the issue. The cookie send by outlook.com (in my case) is

```
DefaultAnchorMailbox
path: "/"
samesite: "None"
value: "***@outlook.de"
```
I searched the [web](https://portswigger.net/web-security/csrf/bypassing-samesite-restrictions) a bit and it seems the issue is that the cookie does not include the `secure` flag.

> When setting a cookie with SameSite=None, the website must also include the Secure attribute, which ensures that the cookie is only sent in encrypted messages over HTTPS. Otherwise, browsers will reject the cookie and it won't be set. 

Even though I receive the cookie via https://, and also send the follow-up request via https://, the cookie is not added to my requests.  This seems to be a recent change in the browser to improve security and outlaw samesite=none .

I changed my code from using `XMLHttpRequest` to using `fetch` and then I got this error:

```
Cookie “DefaultAnchorMailbox” rejected because it has the “SameSite=None” attribute but is missing the “secure” attribute.
```

Can I do something about it? If it helps, I can publish the WIP code.

**Comment by jobisoft** [comment]
@r3dpan @DavidBE-UK : Here is an updated version, which sets the required cookie for connections to `eas.outlook.com`:
[EAS-4-TbSync_4_16.zip](https://github.com/user-attachments/files/19298585/EAS-4-TbSync_4_16.zip)

**Does that work for you?**

Code change is here:
https://github.com/jobisoft/EAS-4-TbSync/commit/377ac45e43ade5e6487df3ca899b3af2586dc769

That means, I am not checking the incoming cookie (which is ignored and not stored) but set the `DefaultAnchorMailbox` cookie based on the provided user name. If the user name does not match the anchor mailbox, I will have to add code to parse the actual returned cookie. I added code to track those, but I was too lazy to implement it.

**Comment by DavidBE-UK** [comment]
Yes! I have my Outlook address book and extra calendars back. Thank you.

**Comment by achmafooma** [comment]
It is also working for me with that latest testing version (4_16). Awesome.

**Comment by jobisoft** [comment]
Big thanks to @r3dpan for doing the network analysis!

**Comment by jobisoft** [comment]
For easier reference: These are the latest test versions:

[TbSync_4_15.zip](https://github.com/user-attachments/files/19266839/TbSync_4_15.zip)
[EAS-4-TbSync_4_16.zip](https://github.com/user-attachments/files/19298585/EAS-4-TbSync_4_16.zip)

Both have now been submitted for review to ATN and should be available for the broader community soon.

**Comment by fonic** [comment]
Works fine for me, too. Well done @jobisoft and @r3dpan!

**Comment by rardcode** [comment]
a

> Found a glitch which may prevent future updates due to aggressive caching.
> 
> * Please uninstall the other pre-release versions.
> * Close Thunderbird
> * Make sure that no Thunderbird process running
> * Start Thunderbird
> * Install the following versions:
> 
> [TbSync_4_15.zip](https://github.com/user-attachments/files/19266839/TbSync_4_15.zip) [EAS-4-TbSync_4_15.zip](https://github.com/user-attachments/files/19266840/EAS-4-TbSync_4_15.zip)

it works for me!
thanks!!

**Comment by jobisoft** [comment]
> Will those _manually_ installed extensions automatically be updated once newer version are available on Thunderbird's extensions store?

Yes!

**Comment by jobisoft** [comment]
> it works for me! thanks!!

@rardcode: You are not using the most recent version.

**Comment by rardcode** [comment]
> > it works for me! thanks!!
> 
> [@rardcode](https://github.com/rardcode): You are not using the most recent version.

4.15

![Image](https://github.com/user-attachments/assets/0f9524cb-8f4a-45a8-be93-267fa049be72)

**Comment by DV-P-Butzelaar** [comment]
New version works for me as well! (Thunderbird 136 with Outlook accounts). Thanks for all the effort!

**Comment by jobisoft** [comment]
> > > it works for me! thanks!!
> > 
> > 
> > [@rardcode](https://github.com/rardcode): You are not using the most recent version.
> 
> TB 136 & TBSync 4.15
> 
> ![Image](https://github.com/user-attachments/assets/0f9524cb-8f4a-45a8-be93-267fa049be72)

EAS-4-TbSync? In your post you wrote 4.15, but 4.16 is the most recent version.

**Comment by rardcode** [comment]
> > > > it works for me! thanks!!
> > > 
> > > 
> > > [@rardcode](https://github.com/rardcode): You are not using the most recent version.
> > 
> > 
> > TB 136 & TBSync 4.15
> 
> EAS-4-TbSync? In your post you wrote 4.15, but 4.16 is the most recent version.

In my post i wrote:

![Image](https://github.com/user-attachments/assets/b09efae6-8ab9-4bc0-a57a-021ae9f1c4d1)

For me work with 

![Image](https://github.com/user-attachments/assets/9209e23c-32d6-4654-a131-73b6d1e5df54)

**Comment by ngandrass** [comment]
Why ever TbSync 4.14 and EAS-4-TBSync 4.14 already worked for me (guess I was lucky?)..,
The newest versions TbSync 4.15 and EAS-4-TbSync 4.16 still work flawlessly here 👍

**Comment by twobaker** [comment]
Thank you very much for your effort! Versions TbSync 4.15 and EAS-4-TbSync 4.16 work here as well.
